[[formatted_heading]]
== Testing of `spans` __and__ **formatting**

The H1 heading above should have backtick (code), italic, and bold formatting applied (in that order). Check in both text body and navigation menus.

[[Smart_quoting]]
=== Smart quoting

This is "double quoted" and 'single quoted' with smart quotes. 

* This double quote is hopefully span:pdf-operator[pass-format:straightquotes["]] not smart quoted. Neither is this single quote span:pdf-operator[pass-format:straightquotes[']] by using `pass` within semantic span markup.

* This double quote is hopefully pass-format:straightquotes[span:pdf-operator["]] not smart quoted. Neither is this single quote pass-format:straightquotes[span:pdf-operator[']] by using semantic span within `pass` markup.


[[Horizontal_lines]]
=== Horizontal lines

There should be a horizontal line below this sentence. This sentence also contains two footnotes footnote:[This is the first footnote from a sentence above and is hopefully rendered with good colour contrast for WCAG.] mid-sentence footnote:[This is the second footnote from a sentence above and is hopefully rendered with good colour contrast for WCAG.].

// "Thematic break" a.k.a. horizontal line
'''

=== Semantic span formatting

This is a sentence with a span:requirement[shall] requirement and a span:recommendation[should] recommendation.

This is a sentence with a span:recommendation[should] recommendation. A forced page break is below this sentence.
See https://docs.asciidoctor.org/asciidoc/latest/blocks/breaks/[].

// Forced page break in PDF
[%always]
<<<

This sentence should always start on a new page in PDF. The following headings have explicit char formatting and semantic spans. This is a citation to to a top level - see <<formatted_heading>>.

[[long_H3]]
=== Heading H3 first but a _very very_ *long* heading to hopefully `trigger` line wrapping of lengthy heading text

==== Heading H4 first span:pdf-operator[((pdf-op))]

===== Heading H5 first with **bold**

====== Heading H6 first with `mono`

This is a sentence with a PDF version span:pdf-version[1.3] as used in PDF specs. It hopefully expands to italic "__(PDF 1.3)__" in blue.

Here is some text using different semantic spans, such as PDF keywords span:pdf-keyword[true] / span:pdf-keyword[false], span:pdf-keyword[stream] / span:pdf-keyword[((endstream))] and span:pdf-keyword[null].

Here is a PDF operator semantic span that is also in the index span:pdf-operator[((pdf-op))]. 

====== Heading H6 second but a __very very__ long heading to hopefully trigger line wrapping of lengthy heading text

Document attribute `:xrefstyle:` is {xrefstyle}. This sentence references other numbered headings, such as <<Smart_quoting>>, <<Horizontal_lines>>, and <<Testing_tables>>.

Here is some different text using semantic spans for PDF operators, such as PDF keywords span:pdf-keyword[RG] / span:pdf-keyword[eg], span:pdf-keyword[cm], and span:pdf-keyword[Do]. 

===== Heading H5 second with _italic_

Some test referencing the full term {{end-of-data marker}}. This is a citation to the second appendix - see <<annex_B>>. 

More test referencing a preferred term {{((EOD marker))}} that is _internally_ wrapped for indexing. This is mentioned using `term` term:[EOD marker]. This is mentioned using `term` with internal wrapping for indexing term:[((EOD marker))]. CANNOT do outer index wrapping of terms or `term` as this causes MN errors "_Empty index term: ..._".

==== Heading H4 second span:pdf-keyword[keyword]

Again, more test referencing the alt term this time with external indexing {{((EOD))}}. 
This is mentioned using `term` with external indexing term:[((EOD))] and `symbol`s symbol:[RGB] and symbol:[stem:[alpha_(bkg)]]. This is a citation to a long H3 with formatting - see <<long_H3>>.
This is a citation to a preface heading - see <<preface_notation>>. 

Testing of when "x" is auto-converted to stem:[xx] when a digit is immediately either side - what markup is needed to stop this auto-conversion?:

* 0x0 - no spaces around "x"
* 0 x 0 - space either side of "x"
* 0x 0 - space after "x"
* 0 x0 - space before "x"
* 0x\0 - use of `\0` after "x"

== Quote blocks

The following is a quote block. It is also citing a bibliographic reference from elsewhere in this document. Note that quotes cannot be used in the 3rd argument. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.

[quote, ISO, "ISO32000_2_AMD1,clause=1.2.3 Some heading in a doc,table=123 - Some table caption"]
____
Graphics objects, other than text objects, span:requirement[shall] be tagged with a **Figure** tag. Here is some very simple math stem:[(x+y)^2]. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. These words include *bold*, _italic_, and `monospaced`.
____

This is the line after the quote block. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.

