== Terms and definitions

[source=ISO32Kb]
=== Terms and definitions

// Testing rendered appearance of T&Ds, preferred and alternate terms. Also check tags!

==== end-of-data marker
preferred:[EOD marker]
alt:[EOD]

one or more bytes that indicate the end of data has been reached 

[.source]
<<IEC_61966_2_1,clause=1.2.3 Some IEC 61966 clause,table=4.5 Table title>>

[NOTE]
====
A block note related to a T&D.

Second paragraph of the "Note X to entry" related to the T&D. Some random text to make a proper lengthy paragraph with line wrapping. Some random text to make a proper lengthy paragraph with line wrapping.
====

[example%collapsible]
====
Example related to a T&D. Some random text to make a proper lengthy paragraph with line wrapping. Some random text to make a proper lengthy paragraph with line wrapping.

Second paragraph of the example related to the T&D. Some random text to make a proper lengthy paragraph with line wrapping. Some random text to make a proper lengthy paragraph with line wrapping.
====

==== second term

definition for a second term without any preferred or alternate term - check the tags

==== third term
preferred:[3rd term]

definition for a third term with preferred term - check the tags


[glossary]
=== Abbreviated terms

// Testing appearance and indexing(!!) of symbols and abbreviated terms

[glossary]
AA::      additional actions
AF::      Associated File
EOD::     end of data duplicate term
EOF::     end of file

[glossary]
=== Symbols

[glossary]
stem:[alpha_(cs) + alpha_(de)]::  source alpha
stem:[alpha_(bkg)]:: background alpha
RGB::                red blue green


