== Testing number formatting

See https://www.metanorma.org/author/topics/inline_markup/semantic-elements/#numbers[] and https://github.com/plurimath/plurimath/[].

The document attributes:

* `:number-presentation-profile-hex-bytes:` has a value of `{number-presentation-profile-hex-bytes}`.
* `:number-presentation-profile-octal:` has a value of `{number-presentation-profile-octal}`.
* `:number-presentation-profile-binary:` has a value of `{number-presentation-profile-binary}`.
* `:number-presentation-profile-unicode:` has a value of `{number-presentation-profile-unicode}`.

Test predefined attribute-based markup for 23 decimal (0x17, 027 octal, 0001 0111 b):

* number:23[]
* number:23[profile=hex-bytes]
* number:23[profile=octal]
* number:23[profile=binary]
* number:23[profile=unicode]

Test predefined attribute-based markup for 234 decimal (0xEA, 352 octal, 1110 1010 b):

* number:234[]
* number:234[profile=hex-bytes]
* number:234[profile=octal]
* number:234[profile=binary]
* number:234[profile=unicode]

Test predefined attribute-based markup for 123,456 decimal (0x5BA0, 55640 octal, 0101 1011 1010 0000 b):

* number:23456[]
* number:23456[profile=hex-bytes]
* number:23456[profile=octal]
* number:23456[profile=binary]
* number:23456[profile=unicode]

This is the last line of text.


