== Testing of `spans` __and__ **formatting**

The H1 heading above should have backtick (code), italic, and bold formatting applied (in that order). Check in both text body and navigation menus.

[[Smart_quoting]]
=== Smart quoting

This is "double quoted" and 'single quoted' with smart quotes. 

* This double quote is hopefully span:pdf-operator[pass-format:straightquotes["]] not smart quoted. Neither is this single quote span:pdf-operator[pass-format:straightquotes[']] by using `pass` within semantic span markup.

* This double quote is hopefully pass-format:straightquotes[span:pdf-operator["]] not smart quoted. Neither is this single quote pass-format:straightquotes[span:pdf-operator[']] by using semantic span within `pass` markup.


[[Horizontal_lines]]
=== Horizontal lines

There should be a horizontal line below this sentence. This sentence also contains two footnotes footnote:[This is the first footnote from a sentence above and is hopefully rendered with good colour contrast for WCAG.] mid-sentence footnote:[This is the second footnote from a sentence above and is hopefully rendered with good colour contrast for WCAG.].

// "Thematic break" a.k.a. horizontal line
'''

=== Semantic span formatting

This is a sentence with a span:requirement[shall] requirement and a span:recommendation[should] recommendation.

This is a sentence with a span:recommendation[should] recommendation. A forced page break is below this sentence.
See https://docs.asciidoctor.org/asciidoc/latest/blocks/breaks/[].

// Forced page break in PDF
[%always]
<<<

This sentence should always start on a new page in PDF.

=== Heading H3 first but a very very long heading to hopefully trigger line wrapping of lengthy heading text

==== Heading H4 first

===== Heading H5 first with **bold**

====== Heading H6 first with `mono`

This is a sentence with a PDF version span:pdf-version[1.3] as used in PDF specs. It hopefully expands to italic "__(PDF 1.3)__" in blue.

Here is some text using different semantic spans, such as PDF keywords span:pdf-keyword[true] / span:pdf-keyword[false], span:pdf-keyword[stream] / span:pdf-keyword[endstream] and span:pdf-keyword[null].

====== Heading H6 second but a __very very__ long heading to hopefully trigger line wrapping of lengthy heading text

Document attribute `:xrefstyle:` is {xrefstyle}. This sentence references other numbered headings, such as <<Smart_quoting>>, <<Horizontal_lines>>, and <<Testing_tables>>.

Here is some different text using semantic spans for PDF operators, such as PDF keywords span:pdf-keyword[RG] / span:pdf-keyword[eg], span:pdf-keyword[cm], and span:pdf-keyword[Do]. 

===== Heading H5 second

Some test referencing the full term {{end-of-data marker}}.

* Bullet list depth 1
** Bullet list depth 2
*** Bullet list depth 3
**** Bullet list depth 4

More test referencing a preferred term {{EOD marker}}. This is mentioned using `term` term:[EOD marker].

==== Heading H4 second

Again, more test referencing the alt term this time {{EOD}}. 
This is mentioned using `term` term:[EOD] and `symbol`s symbol:[RGB] and symbol:[stem:[alpha_(cs)]].


