== Attachments

=== Heading to avoid hanging para warning

Test to see if the *Desc* string of embedded file attachments gets correctly converted as Unicode characters, and MN magic things "smart quotes". The most portable Dec string would be as UTF-16BE but the required 2-byte 0xFE 0xFF BoM is required. Also test for differences between ASCII and PDF default *PDFDocEcoding*.

Also test how files get embedded, and what differences `span:classification.pdf-AFRelationship[Schema]` makes. Need to use a PDF forensic tool to inspect what encoding is used for the chars in <<table_PDFDocEncoding>>! This table is also sortable in HTML.

[[table_PDFDocEncoding]]
.Sortable table of *PDFDocEncoding* vs Unicode
[class="sortable",cols="a,a,a,a",options="header"]
|===
h| **PDFDocEncoding** name | **PDFDocEncoding** value | Unicode codepoint | AsciiDoc
| Breve | 024 dec | U+02D8 | &#x02db;
| Caron | 025 dec | U+02c7 | &#x02c7;
| Dagger | 129 dec | U+2020 | &#x2020;
| Double dagger | 130 dec | U+2021 | &#x2021;
| __invalid!__ | - | U+44CA | [custom-charset: cjk]#&#x44CA;#
|===

Note that the use of the U+44CA glyph in the table above may generate the error: "_Glyph "x" (0x44ca) not available in font "SourceSans3-Regular_"." in *.pdfa.err log file. In this case, the PDF will likely show as "#" as the appearance. The fix is to use a special character mapping as described in https://www.metanorma.org/blog/2024-08-12-fonts-special-chars/ and https://www.metanorma.org/author/topics/inline_markup/text_formatting/#custom-character-sets by setting the document attribute `:presentation-metadata-custom-charset-font:` appropriately to a font with the missing glyphs.

This is a <<Attachment1,reference to Attachment 1 with an AFRelationship>> and this is a <<Attachment2,reference to Attachment 2 also with an AFRelationship>>. <<Attachment3,Attachment 3>> does NOT have an *AFRelationship*.

=== Mentions of bibliographic entries with spans

Here is the first mention of the <<SomeSpec, custom bibliographic entry>>. And here is the mention of the core PDF ISO standard <<ISO32Ka>> or <<ISO32Kb>>.

[bibliography]
== Bibliography

The PDF Association provides https://pdfa.org/sponsored-standards/[sponsored editions of many ISO standards] for no-cost. 

// Testing for https://github.com/relaton/relaton-iso/issues/181
 * [[[ISO32000_2_AMD1,ISO 32000-2:2020/DAmd 1]]]


* [[[IEC_61966_2_1,amend(IEC 61966-2-1)]]]
span:note.display[Some note related to IEC 61966-2-1 with a bare URL https://pdfa.org/ and URL with replacement https://pdfa.org/[PDFa website].]


* [[[IEC_61966_2_1_AMD1,IEC 61966-2-1:1999/AMD1:2003]]]


// Testing of notes related to bibliographic entries. See https://www.metanorma.org/author/topics/sections/bibliography/
// Notes need to be "span:note.display[...]" to render!!!
//* [[[SomeSpec, nofetch(dropid(SomeSpec))]]]
* [[[SomeSpec, (SomeSpec)]]] // see https://github.com/relaton/relaton-db/issues/140
span:title[A fake title]
span:version[1.2]
span:date[2026-04] // has to be YYYY-MM-DD
span:publisher[PDF Association]
span:pages[12]
span:type[standard]
span:uri[https://pdfa.org/]
span:note[This is the first note span associated with a custom bibliographic reference. It is nice and long so that word wrapping and indentation can be more easily viewed in the various output formats.]
span:note[This is a second note span associated with a custom bibliographic reference. It is also nice and long so that word wrapping and indentation can still be easily viewed in the various output formats. Blah blah blah.]
span:note.display[This is the third note span associated with a custom bibliographic reference, but using "display". It is nice and long so that word wrapping and indentation can be more easily viewed in the various output formats. Includes a bare URL https://pdfa.org/.]
span:note.display,warning[This is a fourth note span associated with a custom bibliographic reference, but using "display,warning". It is also nice and long so that word wrapping and indentation can still be easily viewed in the various output formats. Blah blah blah.]

// This is a naked Relaton ISO reference - MN should expand appropriately for the flavour
* [[[ISO32Ka,(ISO 32000-1:2008)ISO 32000-1:2008]]]

// This is a Relaton ISO reference, but with "custom" notes
* [[[ISO32Kb,(ISO 32000-2:2020)amend(ISO 32000-2:2020)]]]
span:note[This is the first note span associated with a Relaton ISO bibliographic reference. It is nice and long so that word wrapping and indentation can be more easily viewed in the various output formats.]
span:note[This is a second note span associated with a Relaton ISO bibliographic reference. It is also nice and long so that word wrapping and indentation can still be easily viewed in the various output formats. Blah blah blah.]
span:note.display[This is the third note span associated with a Relaton ISO bibliographic reference, but using "display". It is nice and long so that word wrapping and indentation can be more easily viewed in the various output formats.]
span:note.display,editorial[This is a fourth note span associated with a Relaton ISO bibliographic reference, but using "display,editorial". It is also nice and long so that word wrapping and indentation can still be easily viewed in the various output formats. Blah blah blah again.]



* [[[Attachment1,attachment:(metanorma-pdfa.yml)]]], span:classification.pdf-AFRelationship[Data], Double-quoted "text" with **bold** and apostrophe's.

* [[[Attachment2,attachment:(metanorma-iso.yml)]]], span:classification.pdf-AFRelationship[Schema], Unicode that don't match PDFDocEncoding. Dagger &#x2020; and Double-dagger &#x2021;.

* [[[Attachment3,attachment:(cspell.json)]]], Attachment without any AFRelationship. A CJK: &#x44CA;.


