== Testing lists

=== Unordered lists

An unordered list:

* Bullet list depth 1. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
** Bullet list depth 2. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
*** Bullet list depth 3. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
**** Bullet list depth 4. we should never go here! This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
***** Bullet list depth 5 - we should never go here!
****** Bullet list depth 6 - we should never go here!

=== Ordered lists

An ordered list:

. [[Point1]]the graphics objects are tagged with a *Figure* structure element (for compliance with the standard), and

. [[Point2]]the *Figure* structure element is a child or descendant of a semantically appropriate block-level structure element (BLSE) footnote:[or an inline-level structure element (ILSE)], and

. [[Point3]]an *ActualText* property is present that reflects the textual content of the graphics objects within the *Figure* structure element, and

. [[Point4]]a *Placement* attribute with a value of _Inline_ is present on the *Figure* structure element.

<<Point3,Point 3>> ensures that the *Figure* structure element possesses the property (an *ActualText* entry) necessary to convey the textual content represented by the graphics objects.

<<Point4,Point 4>> highlights that despite the blah blah.

=== Definition lists

A definition list:

A:: Definition list item for A. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
B:: Definition list item for B
C:: Definition list item for C

And finally a nested definition list:

A:: First part of outer definition list
  AA::: Definition list item for A-A. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
  AB::: Definition list item for A-B
  AC::: Definition list item for A-C
C:: Second part of outer definition list without a child definition list. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
C:: Third part of outer definition list
  CA::: Definition list item for C-A
  CB::: Definition list item for C-B

=== Lists followed by notes

Another unordered list followed immediately by a separate note

* Item 1
* Item 2
* Item 3



NOTE: This is a separate inline note that is NOT associated with Item 3. In the XML includes this outside the `<li>/</li>` but inside the `</ul>` tag!

Another unordered list followed immediately by a separate note

* Item 3
* Item 4
* Item 5

[]

//-

[NOTE]
====
This is a separate note block that is NOT associated with Item 5. In the XML includes this outside the `<li>/</li>` but inside the `</ul>` tag!
====


Another unordered list followed immediately by note that is associated with the last list item

* Item 7
* Item 8
* Item 9 with a note +
[NOTE]
This is a separate note that is associated with Item 9 by using a `+`

The last paragraph of text in the list section.


