== Testing number formatting

See https://www.metanorma.org/author/topics/inline_markup/semantic-elements/#numbers[].

Test explicit `number` markup for 123 decimal:

// 123d = 7Bh = 0x7B = \173 octal = 0111 1011 binary
* number:123[]
* number:123[base=16,base_prefix="0x"]
* number:123[base=16,base_prefix="\(",base_postfix="h)"]
* number:123[base=16,base_postfix="h",hex_capital=true]
* number:123[base=2,group_digits=4,group=' ',base_postfix="b"]
* number:123[base=8,base_prefix="\"]

The document attributes:

* `:number-presentation-profile-hex:` has a value of `{number-presentation-profile-hex}`.
* `:number-presentation-profile-octal:` has a value of `{number-presentation-profile-octal}`.
* `:number-presentation-profile-binary:` has a value of `{number-presentation-profile-binary}`.
* `:number-presentation-profile-unicode:` has a value of `{number-presentation-profile-unicode}`.

Test predefined attribute-based markup for 123,456 decimal:

// Hex = 1E240
* number:123456[profile=hex]

// Octal = 361 100
* number:123456[profile=octal]

// Binary = 0001 1110 0010 0100 0000. How to round up digits to multiple of 4 (padding with zeros)?
* number:123456[profile=binary]

// Unicode formatting: U+XXXX. Always 4 hex digits
* number:12[profile=unicode]


