== Testing lists

=== Unordered lists

An unordered list:

* Bullet list depth 1. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
** Bullet list depth 2. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
*** Bullet list depth 3. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
**** Bullet list depth 4. we should never go here! This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
***** Bullet list depth 5 - we should never go here!
****** Bullet list depth 6 - we should never go here!

Last paragraph so can check spacing from bottom of a list to a following paragraph.

=== Ordered lists

An ordered list:

. [[Point1]]the graphics objects are tagged with a *Figure* structure element (for compliance with the standard), and

. [[Point2]]the *Figure* structure element is a child or descendant of a semantically appropriate block-level structure element (BLSE) footnote:[or an inline-level structure element (ILSE)], and

. [[Point3]]an *ActualText* property is present that reflects the textual content of the graphics objects within the *Figure* structure element, and

. [[Point4]]a *Placement* attribute with a value of _Inline_ is present on the *Figure* structure element.

<<Point3,Point 3>> ensures that the *Figure* structure element possesses the property (an *ActualText* entry) necessary to convey the textual content represented by the graphics objects. <<Point4,Point 4>> highlights that despite the blah blah.

=== Definition lists

A definition list:

A:: Definition list item for A. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
B:: Definition list item for B
C:: Definition list item for C

And finally a nested definition list:

A:: First part of outer definition list
  AA::: Definition list item for A-A. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
  AB::: Definition list item for A-B
  AC::: Definition list item for A-C
B:: Second part of outer definition list without a child definition list. This is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output. his is extra words to cause more wrapping so margins and spacing can be visually checked in the Metanorma output.
C:: Third part of outer definition list
  CA::: Definition list item for C-A.
  CB::: Definition list item for C-B

If the CA definition text is longer (e.g. has "Why is this indent different to above?"), then the gap between the *CA* and the text gets reduced! Last paragraph so can check spacing from bottom of a list to a following paragraph.

=== Lists followed by notes

An unordered list followed immediately by a separate note - this is *INCORRECT* markup:

* Item 1
* Item 2


NOTE: This is a separate inline note that is NOT associated with any list item. The XML includes this outside the `<li>/</li>` but inside the `</ul>` tag.

Another unordered list followed immediately by a separate note with `keep-separate=true` - this is the correct markup and should visually appear as such:

* Item 3
* Item 4


[NOTE,keep-separate=true]
This is a separate note block that is NOT associated with Item 4. It has `keep-separate=true` so should be outdented from the list item.


Another unordered list with a note that is explicitly associated with the last list item - it should appear visually indented reflecting this semantic association:

* Item 5
* Item 6 with a note +
[NOTE]
This is a small block note that is semantically associated with the last top-level list Item 6 by using a `+` and should be indented appropriately.


A multi-level unordered list with a note that is explicitly associated with the last list item - it should appear visually indented reflecting this semantic association:

* Item 7
** Item 8.A with a note +
[NOTE]
This is a small block note that is semantically associated with Item 8.A (depth 2) by using a `+` and should be indented appropriately.


A multi-level ordered list with a note that is explicitly associated with the last list item - it should appear visually indented reflecting this semantic association:

. Item 9
.. Item 10.A with a note +
NOTE: This is a small inline note that is semantically associated with Item 10.A (depth 2) by using a `+` and should be indented appropriately.

A multi-level mixed ordered and unordered lists with a note that is explicitly associated with the last list item - it should appear visually indented reflecting this semantic association:

* Item 10
* Item 11
.. Ordered item 11.A with a note +
[NOTE]
This is a small block note that is semantically associated with Item 11.A (depth 2) by using a `+` and should be indented appropriately.


A ordered top level list with an unordered sublist with a note that is explicitly associated with the last list item - it should appear visually indented reflecting this semantic association:

. Item 11
. Item 12
** Unordered item 12.A with a note +
NOTE: This is a small inline note that is semantically associated with Item 12.A (depth 2) by using a `+` and should be indented appropriately.


The last paragraph of standard text in the list section.


