== Testing of `spans` __and__ **formatting**

The H1 heading above should have backtick (code), italic, and bold formatting applied (in that order). Check in both text body and navigation menus.

[[Smart_quoting]]
=== Smart quoting

This is "double quoted" and 'single quoted' with smart quotes. 

* This double quote is hopefully +"+ not smart quoted. Neither is this single quote +'+ by using a single PLUS SIGN.
* This double quote is hopefully ++"++ not smart quoted. Neither is this single quote ++'++ by using double PLUS SIGNS.
* This double quote is hopefully +++"+++ not smart quoted. Neither is this single quote +++'+++ by using triple PLUS SIGNS.
* This double quote is hopefully pass:["] not smart quoted. Neither is this single quote pass:['] by using `pass:` markup.

[[Horizontal_lines]]
=== Horizontal lines

There should be a horizontal line below this sentence. This sentence also contains two footnotes footnote:[This is the first footnote from a sentence above and is hopefully rendered with good colour contrast for WCAG.] mid-sentence footnote:[This is the second footnote from a sentence above and is hopefully rendered with good colour contrast for WCAG.].

// "Thematic break" a.k.a. horizontal line
'''

=== Semantic span formatting

This is a sentence with a span:requirement[shall] requirement and a span:recommendation[should] recommendation.

This is a sentence with a span:recommendation[should] recommendation. A forced page break is below this sentence.
See https://docs.asciidoctor.org/asciidoc/latest/blocks/breaks/[].

// Forced page break
[%always]
<<<

This sentence should always start on a new page.

=== Heading H3 first

==== Heading H4 first

===== Heading H5 first

====== Heading H6 first

This is a sentence with a PDF version span:pdf-version[1.3] as used in PDF specs. It hopefully expands to italic "__(PDF 1.3)__" in blue.

====== Heading H6 second

Document attribute `:xrefstyle:` is {xrefstyle}. This sentence references other numbered headings, such as <<Smart_quoting>>, <<Horizontal_lines>>, and <<Testing_tables>>.

===== Heading H5 second

Some test referencing the full term {{end-of-data marker}}.

More test referencing a preferred term {{EOD marker}}.

==== Heading H4 second

Again, more test referencing the alt term this time {{EOD}}.


